# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0
version = 1

[[annotations]]
path = [
    "*.png",
    "src/main/helm/**",
    ".github/**",
    ".gitignore",
    "*.md",
    ".devcontainer/**"
]
SPDX-FileCopyrightText = "2025 Deutsche Telekom AG and others"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "gradle/**",
    "gradlew",
    "gradle.properties",
    "gradlew.bat"
]
SPDX-FileCopyrightText = "Copyright 2015 the original author or authors."
SPDX-License-Identifier = "Apache-2.0"