apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lmos-operator.fullname" . }}
  labels:
    {{- include "lmos-operator.labels" . | nindent 4 }}
rules:
  # Permissions to create Custom Resource Definitions (CRDs)
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]

  # Permissions to create custom resources
  - apiGroups: ["{{ .Values.customApiGroup }}"]
    resources:
      {{- range .Values.customResources }}
      - "{{ . }}"
      {{- end }}
    verbs: ["get", "list", "create", "update", "delete", "watch", "patch"]

  # Add permission to access deployments in the apps API group
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Add permission to access pods
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]

  # Add permission to access services
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "list", "watch" ]